### ISSUE TITLE
a question about code error

### ISSUE THREAD

**Issue by Flipped-eloping** [muhammetbalcilar/Multi-Robot-Path-Planning-on-Graphs#1]
Hello,sir!
I downloaded your program and ran it in MATLAB. But it appears the error shown in the picture and I can't solve it. Do you know the cause of the error? Thank you very much!

![image](https://user-images.githubusercontent.com/31913379/48758095-d75c2a00-ecd9-11e8-8bfe-8818cff837bd.png)

**Comment by balcilar** [comment]
hi,
In my side there is no problem. Honestly, I did not see any problem. Did you use the provided demo or you modify it?. please run the original demo and tell me if there is the same error. If yes, then print Cost and curr variable before line6 in finindex.m function and tell me what is the value of Cost and curr just before error.

**Comment by Flipped-eloping** [comment]
> hi,
> In my side there is no problem. Honestly, I did not see any problem. Did you use the provided demo or you modify it?. please run the original demo and tell me if there is the same error. If yes, then print Cost and curr variable before line6 in finindex.m function and tell me what is the value of Cost and curr just before error.

Thank you for your reply. I did not make any changes to the code. When iterated to second times, the value of Cost and curr as shown in the figure. They have different dimensions. And my MATLAB version is 2013a.
![image](https://user-images.githubusercontent.com/31913379/48779643-017e0e00-ed13-11e8-8bb8-2af014ccba93.png)
![image](https://user-images.githubusercontent.com/31913379/48779684-1ce91900-ed13-11e8-83fe-d72d45e2b65d.png)

**Comment by balcilar** [comment]
ok it means it is about old matlab versions matrix computation differences to newer version. anyway to get it run, change line 6 with following code
```
I=sum( abs(Cost(:,1:end-1)-repmat(curr,size(Cost,1),1))');
```

**Comment by Flipped-eloping** [comment]
> I=sum( abs(Cost(:,1:end-1)-repmat(curr,size(Cost,1),1))')；

Succeed! you are really awesome!Thank you again!
